### ISSUE TITLE
Software version on applications

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/FlightSoftwareWorkspace#3]
We need to implement a GetVersion command on all boards. Current idea is to have, as part of the version, the shortened hash of the FlightSoftwareWorkspace, the hash of the repository and a flag that states if the repositories are dirty or not.

I would add it to the SoftwareUpdate service.

**Comment by CasperBroekhuizen** [comment]
Related to https://github.com/DelfiSpace/COMMS_FlightSoftware/issues/3

**Comment by CasperBroekhuizen** [comment]
Workspace version number has been added to the makefile, and a dirty marker has been added to the front of the version number (D for Dirty) (in https://github.com/DelfiSpace/COMMS_FlightSoftware/commit/732fc41047241669a6b24d99fb820cb6d39ffa44):
![image](https://user-images.githubusercontent.com/17972261/72077185-1f337b80-32f7-11ea-894b-d2072489e80d.png)

Has to be checked for compatibility with Mac, and the Service has yet to be extended/updated

**Comment by CasperBroekhuizen** [comment]
Tested and compatible with Mac.

Issue however is the location of the service and the makefile. Having the service and makefile in DelfiPQCore, this causes the Version numbers to not be included in the build of a module (in this example COMMS):
![image](https://user-images.githubusercontent.com/17972261/72136165-7b92ab80-3388-11ea-9a7b-70bfc635c4c7.png)

Having the service in DelfiPQCore and the makefile in the Module, makes the version numbers accessible to the Submodule again, but not to the Service that was build in a separate dependency: 
![image](https://user-images.githubusercontent.com/17972261/72136591-6bc79700-3389-11ea-8a40-b3a46fcc6056.png)

A work around for this problems should be that the version numbers are passed to the Service in the submodule's main.cpp after the service is created.

**Comment by StefanoSperetta** [comment]
Can you pass the defines in the constructor of the service? This way the service is in DelfiPQCore but the versions (and the makefile) are in the top-level projects (like COMMS)?

**Comment by CasperBroekhuizen** [comment]
Giving the Version number in the constructor of the VersionService works fine! The version number service has been moved to a seperate branch of PQCore (https://github.com/DelfiSpace/DelfiPQcore/commit/948cb6a3094a15b3345aa86c5dee28af67184979). Every project should put the version number in the service constructor and have the makefile.defs in the repository (similar to https://github.com/DelfiSpace/COMMS_FlightSoftware/commit/6030ff42a304d5f772df039555b1aa398be8f28e). Also the Project Software Version and Workspace Version Number have been merged into one (8-byte value): 
![image](https://user-images.githubusercontent.com/17972261/72248533-b2bac400-35f7-11ea-8500-754d0d96aa09.png)


@jhaenen will merge the SoftwareVersionService with the SoftwareUpdateVersion on a branch of DelfiPQCore (https://github.com/DelfiSpace/DelfiPQcore/tree/UpdateService)

**Comment by StefanoSperetta** [comment]
Sounds great! I would stick to this plan and as soon as we have a "merged" version of the service (not necessarily with the full software update protocol, but at least with final function names), I would push it to master in DelfiPQCore and start implementing it in the different applications.

Michael in the meantime can also work on the XML to nicely print the versions  in the GUI...

**Comment by CasperBroekhuizen** [comment]
software version is merged with the software update service in commit https://github.com/DelfiSpace/DelfiPQcore/commit/cc7d535ad114452446170baff30c0c866e880208 

However, the problem was that the software-version is baked into the file, and is hard to extract from the binary file. Workaround for now is to edit the makefile to write the software version to an external file (echo ${SW_GIT_HASH} > SW_VERSION) and re-use it during the post-build steps ( ${cat SW_VERSION} ), this can be seen in the EPS Software update branch, where the SWVersion is put in the name of the .bin file. (commit https://github.com/DelfiSpace/EPS_FlightSoftware/commit/5bc972b9f1e65462e66be000993e158a8a2cb7ab)

**Comment by StefanoSperetta** [comment]
It looks good to me. I was thinking if we can simplify it a bit and maybe we could move the slot definition to an .h file in DelfiPQCore and just leave the selection of the slot in a file inside the project.

I would take off the main.cpp files the stringification functions (#define xstr(s) str(s), etc) and define a macro like GET_SW_VERSION (also in DelfiPQCore) that we can call in the main files instead of the #ifndef SW_VERSION code block.

But this is an optimisation, I think

**Comment by CasperBroekhuizen** [comment]
In commit https://github.com/DelfiSpace/EPS_FlightSoftware/commit/5bc972b9f1e65462e66be000993e158a8a2cb7ab I moved the slot definition and selection to a seperate header file (SLOT_SELECT.h).

I agree with moving the stringification functions out of the main.cpp.
However, moving the GET_SW_VERSION into DelfiPQCore will break the functionality, as the SW_VERSION is a macro that is included during build of the Sub-module (not delfiPQCore). Maybe this new SLOT_SELECT.h is a good location for it, however it will make it required to keep it in the main project folder.

**Comment by CasperBroekhuizen** [comment]
Duplicate closed (https://github.com/DelfiSpace/DelfiPQcore/issues/10)
