### ISSUE TITLE
Create a PQ9Frame cpp object

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/FlightSoftwareWorkspace#4]
Service and Request fields in the XML are not handled by a getter/setter.

SetSize command is also "weird" because the SetSize is not setting the size of the payload but it also includes the service and request....

**Comment by CasperBroekhuizen** [comment]
The PQ9Frame is shaped as follows:

[DESTINATION] [SIZE] [SOURCE] [SERVICE] [RESPONSE] {SERVICEDATA} [CRC_1] [CRC_2]

Currently the PayloadSize excludes the Destination, Size, Source and CRCBytes, but does include the Service and Response. Meaning that a simple 'yes' reply has a FrameSize of 7 bytes, but a payloadSize of 2 bytes (Service + Response). 

Does this makes sense, or should the payloadSize be 0? In this way the 'Size' byte will mean the extra payload send back by the service (which is free to design for the user). which could contain information, values or even error-codes. Personally I feel it might be unintuitive that the Payloadsize is always >2 if the Service and Response byte are always required to send back.

The Response byte can be standardized to:
     static const unsigned char RESPONSE_ERROR = 0;
     static const unsigned char RESPONSE_REQUEST = 1;
     static const unsigned char RESPONSE_REPLY = 2;

Any thoughts or input is very welcome (@StefanoSperetta , @MFvandenBos ).

**Comment by MFvandenBos** [comment]
I think your suggestion is the easiest solution.

**Comment by StefanoSperetta** [comment]
It is very important for me to keep it consistent with the XML file (as my wish would be in the future to generate automatically from XML all getters/setters/objects for data transfer.

The size implemented like this was chosen to create a "standard" PQ9 frame and leave (only with the networking bits in there) and leave the higher level protocol free.

At this stage we might create an intermediate frame containing the service and the response (and the rest of the payload) which would allow not to touch the PQ9 frame... not sure if this would help in the overall implementation... Very much in doubt at this stage...

**Comment by CasperBroekhuizen** [comment]
I see, I can keep the PQFrame similar to how it is now and lift the '[service][response][servicedata]' construction to a higher protocol level (PQ9ServicePacket). This approach does allow services that use PQ9Frame exclusively to keep working.

**Comment by CasperBroekhuizen** [comment]
As discussed today, a PQ9Frame is handled by the CommandHandler which deals with the networking layer, whereas a PQ9Packet/Message is handled by the services (Application Layer). The size byte indicates the size of the Packet/Message (and is thus correct for SIZE=2 on a simple response):

Network Layer:
[Destination] [Msg Size] [Source] [Msg] [CRC_1] [CRC_2]

Application layer:
[Msg] = [Service] [Response] [Payload bytes]

**Comment by CasperBroekhuizen** [comment]
Fixed in https://github.com/DelfiSpace/DelfiPQcore/commit/d68ee6f83c1c135ce324a6a5420feb4de45c8efe and https://github.com/DelfiSpace/DelfiPQcore/commit/a22cd21b9745ee0a66960cfa21dc470674c77c20
